services:
  order-db:
    image: postgres:16
    environment:
      POSTGRES_DB: order
      POSTGRES_USER: order
      POSTGRES_PASSWORD: order123
    ports:
      - "5433:5432"

  order:
    build:
      context: .
      dockerfile: api/order-service/Dockerfile
    ports:
      - "8081:8081"
    environment:
      DATABASE_HOST: order-db
      DATABASE_PORT: 5432
      DATABASE_DB: order
      DATABASE_USERNAME: order
      DATABASE_PASSWORD: order123
    depends_on:
      - order-db
